# ESP Home Configure yaml

esphome:
  name: t-camera-plus
  platform: ESP32
  board: esp32dev

wifi:
  ssid: "ssid"
  password: "password"

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

mqtt:
  broker: 'ip address'
  # username: 'user'
  #password: 'password'

# ttgo_camera_mini configuration
esp32_camera:
  external_clock:
    pin: GPIO4
    frequency: 20MHz
  i2c_pins:
    sda: GPIO18
    scl: GPIO23
  data_pins: [GPIO34, GPIO13, GPIO26, GPIO35, GPIO39, GPIO38, GPIO37, GPIO36]
  vsync_pin: GPIO5
  href_pin: GPIO27
  pixel_clock_pin: GPIO25
  #power_down_pin: -1

  # Image settings
  name: TTGO T-Camera Plus
