esphome:
  name: t-camear-v17
  platform: ESP32
  board: esp32dev

wifi:
  ssid: "ssid"
  password: "password"

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

mqtt:
  broker: 'ip address'
  # username: 'user'
  # password: 'password'

# ttgo_camearv16 configuration
esp32_camera:
  external_clock:
    pin: GPIO32
    frequency: 20MHz
  i2c_pins:
    sda: GPIO13
    scl: GPIO12
  data_pins: [GPIO5, GPIO14, GPIO4, GPIO15, GPIO18, GPIO23, GPIO36, GPIO39]
  vsync_pin: GPIO27
  href_pin: GPIO25
  pixel_clock_pin: GPIO19

  # Image settings
  name: T-Cameara v1.7
